CREATE TABLE analyst_estimate (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id  UUID NOT NULL,
    analyst_firm VARCHAR(100),
    target_price DECIMAL(19, 4),
    rating_label VARCHAR(10),
    target_date  DATE,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analyst_estimate_security
        FOREIGN KEY (security_id) REFERENCES security(id) ON DELETE CASCADE
);

CREATE INDEX idx_analyst_estimate_security_date
    ON analyst_estimate(security_id, target_date DESC);
