import { useMutation, useQuery } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { apiFetch } from '../api/client'

type Detail = { symbol: string; companyName: string; sector: string | null; exchange: string | null; country: string | null; currency: string | null; marketCap: number | null; description: string | null; website: string | null; currentPrice: number | null; priceDate: string | null; revenue: number | null; netIncome: number | null; fcf: number | null; eps: number | null; bvps: number | null; pe: number | null; roic: number | null; dividendYield: number | null; dataAsOf: string | null }
type Financials = { annuals: Array<{ fiscalYear: number; revenue: number | null; netIncome: number | null; fcf: number | null; eps: number | null; bvps: number | null }>; quarters: Array<{ period: string; revenue: number | null; netIncome: number | null; fcf: number | null; eps: number | null }>; ttm: { revenue: number | null; netIncome: number | null; fcf: number | null; eps: number | null } | null }
type Ratios = { ratios: Array<{ date: string; pe: number | null; roic: number | null; roe: number | null; debtToEquity: number | null; grossMargin: number | null; dividendYield: number | null }> }
type Valuation = { currentPrice: number | null; dcf: { base: number | null; low: number | null; high: number | null } | null; grahamNumber: number | null; ddmValue: number | null; compositeFairValue: number | null; marginOfSafety: number | null; mosLow: number | null; mosHigh: number | null; recommendation: string | null; analystEstimates: { meanTarget: number | null; lowTarget: number | null; highTarget: number | null; analystCount: number; consensus: string | null } | null; dataAsOf: string | null; disclaimer: string }
type Dividends = { history: Array<{ exDividendDate: string | null; paymentDate: string | null; amount: number | null; currency: string | null }>; streak: number; cagr3y: number | null; cagr5y: number | null; cagr10y: number | null }
type Growth = { revenue: Metrics; fcf: Metrics; eps: Metrics }; type Metrics = { cagr3y: number | null; cagr5y: number | null; cagr10y: number | null }
type Insiders = { trades: Array<{ transactionDate: string; name: string | null; title: string | null; transactionType: string | null; shares: number | null; pricePerShare: number | null; totalValue: number | null }> }
type Peers = { peers: Array<{ symbol: string; companyName: string; currentPrice: number | null; compositeFairValue: number | null; marginOfSafety: number | null; totalScore: number | null; pe: number | null; roic: number | null }> }
type Tab = 'overview' | 'financials' | 'ratios' | 'health' | 'valuation' | 'dividends' | 'growth' | 'insider'

const tabs: Array<[Tab, string]> = [['overview', 'Overview'], ['financials', 'Financials'], ['ratios', 'Ratios'], ['health', 'Financial health'], ['valuation', 'Valuation'], ['dividends', 'Dividends'], ['growth', 'Growth'], ['insider', 'Insider']]
const money = (value: number | null | undefined, currency = 'USD') => value == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 2, notation: Math.abs(value) >= 1000000 ? 'compact' : 'standard' }).format(value)
const number = (value: number | null | undefined) => value == null ? '—' : new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(value)
const percent = (value: number | null | undefined) => value == null ? '—' : `${number(value)}%`
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—'

class ApiError extends Error { constructor(message: string, readonly status: number) { super(message) } }
async function json<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await apiFetch(path, init)
  if (!response.ok) {
    const body = await response.json().catch(() => null) as { message?: string; detail?: string; error?: string } | null
    throw new ApiError(body?.message || body?.detail || body?.error || `Request failed (${response.status}).`, response.status)
  }
  return response.json() as Promise<T>
}
function ErrorPopup({ error, retry, dismiss }: { error: unknown; retry: () => void; dismiss: () => void }): JSX.Element | null {
  if (!error) return null
  const message = error instanceof Error ? error.message : 'Something went wrong while loading this research data.'
  return <div role="alertdialog" aria-modal="false" aria-labelledby="api-error-title" className="fixed bottom-5 right-5 z-50 max-w-md rounded-xl border border-rose-300/30 bg-slate-900 p-5 shadow-2xl shadow-black/40"><h2 id="api-error-title" className="font-semibold text-rose-100">Data request unavailable</h2><p className="mt-2 text-sm leading-6 text-slate-300">{message}</p><div className="mt-4 flex gap-3"><button onClick={retry} className="rounded-lg bg-rose-300 px-3 py-2 text-sm font-semibold text-slate-950">Try again</button><button onClick={dismiss} className="rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-200">Dismiss</button></div></div>
}
function Loading(): JSX.Element { return <div className="py-12 text-center text-slate-400">Loading live research data…</div> }
function Unavailable({ children = 'This data is not available for the selected security.' }: { children?: ReactNode }): JSX.Element { return <p className="rounded-xl border border-slate-700 bg-slate-950/40 p-4 text-sm text-slate-400">{children}</p> }
function Card({ title, children }: { title: string; children: ReactNode }): JSX.Element { return <section className="rounded-xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-base font-semibold text-white">{title}</h2><div className="mt-4">{children}</div></section> }
function Metric({ label, value }: { label: string; value: string }): JSX.Element { return <div className="rounded-lg bg-slate-950/55 p-3"><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-medium text-white">{value}</dd></div> }
function Chart({ data, lines, bar = false }: { data: Array<Record<string, number | string | null>>; lines: Array<[string, string]>; bar?: boolean }): JSX.Element {
  if (!data.length) return <Unavailable />
  const Component = bar ? BarChart : LineChart
  return <div className="h-72 w-full" role="img" aria-label={`Historical chart: ${lines.map(([, label]) => label).join(', ')}`}><ResponsiveContainer><Component data={data}><CartesianGrid stroke="#334155" strokeDasharray="3 3" /><XAxis dataKey="label" stroke="#94a3b8" /><YAxis stroke="#94a3b8" tickFormatter={(v) => number(v)} /><Tooltip formatter={(v) => number(Number(v))} contentStyle={{ background: '#0f172a', border: '1px solid #334155' }} /><Legend />{lines.map(([key, label], index) => bar ? <Bar key={key} dataKey={key} name={label} fill={['#34d399', '#60a5fa', '#fbbf24'][index]} /> : <Line key={key} type="monotone" dataKey={key} name={label} stroke={['#34d399', '#60a5fa', '#fbbf24', '#f472b6'][index]} strokeWidth={2} dot={false} connectNulls />)}</Component></ResponsiveContainer></div>
}

export function SecurityDetailPage(): JSX.Element {
  const { symbol: rawSymbol = '' } = useParams(); const symbol = rawSymbol.trim().toUpperCase(); const [tab, setTab] = useState<Tab>('overview'); const [popup, setPopup] = useState<{ error: unknown; retry: () => void } | null>(null)
  const detail = useQuery({ queryKey: ['security', symbol, 'detail'], enabled: !!symbol, queryFn: () => json<Detail>(`/api/v1/securities/${encodeURIComponent(symbol)}`), retry: false })
  const financials = useQuery({ queryKey: ['security', symbol, 'financials'], enabled: tab === 'financials' || tab === 'health', queryFn: () => json<Financials>(`/api/v1/securities/${encodeURIComponent(symbol)}/financials`), retry: false })
  const ratios = useQuery({ queryKey: ['security', symbol, 'ratios'], enabled: tab === 'ratios' || tab === 'health', queryFn: () => json<Ratios>(`/api/v1/securities/${encodeURIComponent(symbol)}/ratios`), retry: false })
  const valuation = useQuery({ queryKey: ['security', symbol, 'valuation'], enabled: tab === 'valuation', queryFn: () => json<Valuation>(`/api/v1/securities/${encodeURIComponent(symbol)}/valuation`), retry: false })
  const dividends = useQuery({ queryKey: ['security', symbol, 'dividends'], enabled: tab === 'dividends', queryFn: () => json<Dividends>(`/api/v1/securities/${encodeURIComponent(symbol)}/dividends`), retry: false })
  const growth = useQuery({ queryKey: ['security', symbol, 'growth'], enabled: tab === 'growth', queryFn: () => json<Growth>(`/api/v1/securities/${encodeURIComponent(symbol)}/growth`), retry: false })
  const insiders = useQuery({ queryKey: ['security', symbol, 'insiders'], enabled: tab === 'insider', queryFn: () => json<Insiders>(`/api/v1/securities/${encodeURIComponent(symbol)}/insiders`), retry: false })
  const peers = useQuery({ queryKey: ['security', symbol, 'peers'], enabled: tab === 'overview', queryFn: () => json<Peers>(`/api/v1/securities/${encodeURIComponent(symbol)}/peers`), retry: false })
  const watchlist = useMutation({ mutationFn: () => json('/api/v1/watchlist', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ symbol }) }) })
  const anyError = [detail, financials, ratios, valuation, dividends, growth, insiders, peers].find((query) => query.isError)
  useEffect(() => {
    if (anyError?.isError) setPopup({ error: anyError.error, retry: () => void anyError.refetch() })
  }, [anyError?.error])
  if (!symbol) return <main className="mx-auto max-w-3xl px-5 py-10"><Unavailable>Choose a security from the screener to begin research.</Unavailable></main>
  if (detail.isLoading) return <main className="mx-auto max-w-7xl px-5 py-10"><Loading /></main>
  if (!detail.data) return <main className="mx-auto max-w-3xl px-5 py-10"><Unavailable>Security data could not be loaded. Return to the <Link className="text-emerald-300 underline" to="/screener">screener</Link> and try again.</Unavailable></main>
  const d = detail.data; const currency = d.currency || 'USD'; const annual = [...(financials.data?.annuals || [])].reverse().map((item) => ({ label: String(item.fiscalYear), ...item })); const ratioData = [...(ratios.data?.ratios || [])].reverse().map((item) => ({ label: item.date.slice(0, 4), ...item }));
  const openTab = (next: Tab) => { setTab(next); setPopup(null) }
  const content = (): JSX.Element => {
    if (tab === 'overview') return <div className="grid gap-5 lg:grid-cols-2"><Card title="Business context"><p className="leading-7 text-slate-300">{d.description || 'Company description is not available.'}</p>{d.website && <a className="mt-4 inline-block text-sm font-medium text-emerald-300 underline" href={d.website} target="_blank" rel="noreferrer">Visit company website</a>}</Card><Card title="Current fundamentals"><dl className="grid grid-cols-2 gap-3"><Metric label="Revenue" value={money(d.revenue, currency)} /><Metric label="Net income" value={money(d.netIncome, currency)} /><Metric label="Free cash flow" value={money(d.fcf, currency)} /><Metric label="ROIC" value={percent(d.roic)} /><Metric label="P/E" value={number(d.pe)} /><Metric label="Dividend yield" value={percent(d.dividendYield)} /></dl></Card><Card title="Sector peers"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Company</th><th>MoS</th><th>Score</th></tr></thead><tbody>{peers.isLoading ? <tr><td colSpan={3} className="py-4 text-slate-400">Loading peers…</td></tr> : peers.data?.peers.length ? peers.data.peers.map((peer) => <tr key={peer.symbol} className="border-t border-slate-800"><td className="py-3"><Link className="font-medium text-emerald-300" to={`/securities/${peer.symbol}`}>{peer.symbol}</Link><span className="ml-2 text-slate-400">{peer.companyName}</span></td><td>{percent(peer.marginOfSafety)}</td><td>{number(peer.totalScore)}</td></tr>) : <tr><td colSpan={3} className="py-4 text-slate-400">No peer comparison is available.</td></tr>}</tbody></table></div></Card><Card title="Data context"><dl className="grid grid-cols-2 gap-3"><Metric label="Data as of" value={date(d.dataAsOf)} /><Metric label="Price date" value={date(d.priceDate)} /><Metric label="Exchange" value={d.exchange || '—'} /><Metric label="Country" value={d.country || '—'} /></dl></Card></div>
    if (tab === 'financials') return financials.isLoading ? <Loading /> : <div className="space-y-5"><Card title="Annual performance"><Chart data={annual} lines={[['revenue', 'Revenue'], ['netIncome', 'Net income'], ['fcf', 'Free cash flow']]} bar /></Card><Card title="Latest reporting context"><dl className="grid gap-3 sm:grid-cols-3"><Metric label="TTM revenue" value={money(financials.data?.ttm?.revenue, currency)} /><Metric label="TTM net income" value={money(financials.data?.ttm?.netIncome, currency)} /><Metric label="TTM free cash flow" value={money(financials.data?.ttm?.fcf, currency)} /></dl></Card></div>
    if (tab === 'ratios') return ratios.isLoading ? <Loading /> : <div className="space-y-5"><Card title="Returns and valuation"><Chart data={ratioData} lines={[['pe', 'P/E'], ['roic', 'ROIC'], ['roe', 'ROE']]} /></Card><Card title="Capital structure"><Chart data={ratioData} lines={[['debtToEquity', 'Debt / equity'], ['grossMargin', 'Gross margin'], ['dividendYield', 'Dividend yield']]} /></Card></div>
    if (tab === 'health') return financials.isLoading || ratios.isLoading ? <Loading /> : <div className="space-y-5"><Card title="Earnings and cash-generation trend"><Chart data={annual} lines={[['revenue', 'Revenue'], ['netIncome', 'Net income'], ['fcf', 'Free cash flow']]} /></Card><Card title="Resilience indicators"><Chart data={ratioData} lines={[['debtToEquity', 'Debt / equity'], ['roic', 'ROIC'], ['grossMargin', 'Gross margin']]} /><p className="mt-4 text-sm leading-6 text-slate-400">These are trend indicators, not universal safety ratings. Compare capital structure and profitability with the company’s sector and business model. Short/long-term debt, liquidity, interest coverage, and payout coverage are not supplied by the current API and are deliberately shown as unavailable.</p></Card></div>
    if (tab === 'valuation') return <ValuationTab symbol={symbol} currency={currency} query={valuation} />
    if (tab === 'dividends') return dividends.isLoading ? <Loading /> : <div className="space-y-5"><Card title="Dividend history"><Chart data={[...(dividends.data?.history || [])].reverse().map((x) => ({ label: (x.paymentDate || x.exDividendDate || '').slice(0, 7), amount: x.amount }))} lines={[['amount', 'Dividend per share']]} bar /></Card><Card title="Income profile"><dl className="grid gap-3 sm:grid-cols-4"><Metric label="Consecutive years" value={number(dividends.data?.streak)} /><Metric label="3-year CAGR" value={percent(dividends.data?.cagr3y)} /><Metric label="5-year CAGR" value={percent(dividends.data?.cagr5y)} /><Metric label="10-year CAGR" value={percent(dividends.data?.cagr10y)} /></dl><p className="mt-4 text-sm text-slate-400">Payout and coverage data are not supplied by the current endpoint.</p></Card></div>
    if (tab === 'growth') return growth.isLoading ? <Loading /> : <Card title="Annual compound growth"><GrowthTable data={growth.data} /></Card>
    return insiders.isLoading ? <Loading /> : <Card title="Recent insider transactions"><div className="overflow-x-auto"><table className="min-w-[680px] w-full text-left text-sm"><thead className="border-b border-slate-700 text-slate-400"><tr><th className="pb-3">Date</th><th>Name</th><th>Role</th><th>Type</th><th>Shares</th><th>Value</th></tr></thead><tbody>{insiders.data?.trades.length ? insiders.data.trades.map((trade, i) => <tr key={`${trade.transactionDate}-${i}`} className="border-b border-slate-800"><td className="py-3">{date(trade.transactionDate)}</td><td>{trade.name || '—'}</td><td>{trade.title || '—'}</td><td>{trade.transactionType || '—'}</td><td>{number(trade.shares)}</td><td>{money(trade.totalValue, currency)}</td></tr>) : <tr><td colSpan={6} className="py-5 text-slate-400">No insider-trade history is available.</td></tr>}</tbody></table></div></Card>
  }
  return <main className="mx-auto max-w-7xl space-y-6 px-5 py-8 lg:px-8"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><Link className="text-sm font-medium text-emerald-300 hover:text-emerald-200" to="/screener">← Back to screener</Link><p className="mt-5 text-xs font-semibold uppercase tracking-[.22em] text-emerald-300">Security research</p><h1 className="mt-2 text-3xl font-semibold text-white sm:text-4xl">{d.companyName} <span className="text-slate-400">({d.symbol})</span></h1><p className="mt-2 text-sm text-slate-400">{[d.sector, d.country, d.exchange].filter(Boolean).join(' · ') || 'Profile context unavailable'}</p></div><div className="flex flex-wrap gap-3 md:justify-end"><div className="rounded-xl border border-slate-700 bg-slate-950/60 px-4 py-3"><span className="block text-xs uppercase tracking-wide text-slate-500">Current price</span><span className="mt-1 block text-xl font-semibold text-white">{money(d.currentPrice, currency)}</span><span className="text-xs text-slate-500">{date(d.priceDate)}</span></div><Link to={`/securities/${encodeURIComponent(symbol)}/review`} className="rounded-xl border border-emerald-400/40 px-4 py-3 text-sm font-semibold text-emerald-200 hover:bg-emerald-400/10">Open in-depth review</Link><button disabled={watchlist.isPending} onClick={() => watchlist.mutate()} className="rounded-xl bg-emerald-400 px-4 py-3 text-sm font-semibold text-slate-950 disabled:opacity-60">{watchlist.isPending ? 'Adding…' : 'Add to watchlist'}</button></div></div>{watchlist.isSuccess && <p role="status" className="mt-4 text-sm text-emerald-200">Added to your watchlist.</p>}{watchlist.isError && <p role="alert" className="mt-4 text-sm text-rose-200">{watchlist.error instanceof Error ? watchlist.error.message : 'Could not add this security to your watchlist.'}</p>}</section><div role="tablist" aria-label="Security research sections" className="flex gap-2 overflow-x-auto border-b border-slate-800 pb-2">{tabs.map(([key, label]) => <button key={key} type="button" role="tab" aria-selected={tab === key} onClick={() => openTab(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium transition ${tab === key ? 'bg-emerald-400 text-slate-950' : 'text-slate-300 hover:bg-slate-800 hover:text-white'}`}>{label}</button>)}</div><div role="tabpanel">{content()}</div>{popup && <ErrorPopup error={popup.error} retry={popup.retry} dismiss={() => setPopup(null)} />}</main>
}

function GrowthTable({ data }: { data?: Growth }): JSX.Element { const rows: Array<[string, Metrics | undefined]> = [['Revenue', data?.revenue], ['Free cash flow', data?.fcf], ['EPS', data?.eps]]; return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-700 text-slate-400"><tr><th className="pb-3">Metric</th><th>3 years</th><th>5 years</th><th>10 years</th></tr></thead><tbody>{rows.map(([label, values]) => <tr key={label} className="border-b border-slate-800"><th className="py-3 font-medium text-white">{label}</th><td>{percent(values?.cagr3y)}</td><td>{percent(values?.cagr5y)}</td><td>{percent(values?.cagr10y)}</td></tr>)}</tbody></table></div> }
function ValuationTab({ symbol, currency, query }: { symbol: string; currency: string; query: { isLoading: boolean; data?: Valuation } }): JSX.Element { const [form, setForm] = useState({ wacc: '0.10', growthY1Y5: '0.06', growthY6Y10: '0.04', terminalRate: '0.025' }); const custom = useMutation({ mutationFn: () => json<{ dcfFairValue?: number }>(`/api/v1/securities/${encodeURIComponent(symbol)}/valuation/dcf`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...Object.fromEntries(Object.entries(form).map(([k, v]) => [k, Number(v)])), requiredReturn: null, dividendGrowthRate: null }) }) }); if (query.isLoading) return <Loading />; const v = query.data; return <div className="grid gap-5 xl:grid-cols-2"><Card title="Fair value and margin of safety"><dl className="grid grid-cols-2 gap-3"><Metric label="Market price" value={money(v?.currentPrice, currency)} /><Metric label="Composite fair value" value={money(v?.compositeFairValue, currency)} /><Metric label="Margin of safety" value={percent(v?.marginOfSafety)} /><Metric label="Scenario range" value={`${percent(v?.mosLow)} – ${percent(v?.mosHigh)}`} /><Metric label="DCF base" value={money(v?.dcf?.base, currency)} /><Metric label="Recommendation" value={v?.recommendation || '—'} /></dl>{v?.analystEstimates && <p className="mt-4 text-sm text-slate-400">Analyst consensus: {v.analystEstimates.consensus || '—'} ({v.analystEstimates.analystCount} estimates)</p>}<p className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100">{v?.disclaimer || 'This is a decision-support tool, not investment advice (MiFID II).'}</p></Card><Card title="Custom DCF assumptions"><form onSubmit={(e) => { e.preventDefault(); custom.mutate() }} className="grid gap-3 sm:grid-cols-2">{Object.entries(form).map(([key, value]) => <label key={key} className="text-sm text-slate-300">{key === 'growthY1Y5' ? 'Growth years 1–5' : key === 'growthY6Y10' ? 'Growth years 6–10' : key === 'terminalRate' ? 'Terminal rate' : 'WACC'}<input required type="number" step="0.001" value={value} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className="mt-1 block w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label>)}<button className="rounded-lg bg-emerald-400 px-4 py-2 font-semibold text-slate-950 sm:col-span-2" disabled={custom.isPending}>{custom.isPending ? 'Calculating…' : 'Run custom DCF'}</button></form>{custom.isError && <p role="alert" className="mt-3 text-sm text-rose-200">{custom.error instanceof Error ? custom.error.message : 'Custom valuation could not be calculated.'}</p>}{custom.data && <p className="mt-4 text-sm text-emerald-200">Custom valuation calculated. See fair value: {money(custom.data.dcfFairValue, currency)}.</p>}</Card></div> }
